vich_uploader:
    db_driver: orm

    mappings:
        thumbnails:
            uri_prefix: /images/thumbnails
            upload_destination: '%kernel.project_dir%/public/images/thumbnails'
        images:
            uri_prefix: /frontendImages/Homeimages/images
            upload_destination: '%kernel.project_dir%/public/frontendImages/Homeimages/images'
        views:
            uri_prefix: /frontendImages/Aboutimages/views
            upload_destination: '%kernel.project_dir%/public/frontendImages/Aboutimages/views'
        pictures:
            uri_prefix: /frontendImages/Eventsimages/pictures
            upload_destination: '%kernel.project_dir%/public/frontendImages/Eventsimages/pictures'
        figures:
            uri_prefix: /frontendImages/Courseimages/figures
            upload_destination: '%kernel.project_dir%/public/frontendImages/Courseimages/figures'